# Generated by Django 2.1.5 on 2021-07-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210729_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Catergories'},
        ),
    ]
